package.path = './?.lua;./mac-deskpilot/?.lua;' .. package.path
local Births = require('deskpilot_births')
local count = 0
local function test(name, fn) fn(); count = count + 1; print('ok ' .. name) end
local function row(id, pid, layer)
  return { kCGWindowNumber = id, kCGWindowOwnerPID = pid, kCGWindowLayer = layer == nil and 0 or layer }
end
local function baseline()
  local t = Births.new(); t:observe({row(1, 10)}, true, 100); return t
end
local function pending()
  local t = baseline(); t:observe({row(1, 10), row(2, 10)}, true, 101); return t
end

test('startup windows establish a baseline without births', function()
  local t = Births.new(); assert(not t:ready())
  assert(t:observe({row(1, 10), row(2, 20)}, true, 100)); assert(t:ready())
  assert(not t:take(1, 10, 100)); assert(not t:take(2, 20, 100))
end)
test('empty successful query establishes a baseline', function()
  local t = Births.new(); t:observe({}, true, 100); assert(t:ready())
  t:observe({row(1, 10)}, true, 101); assert(t:take(1, 10, 101))
end)
test('failed initial query cannot establish a baseline', function()
  local t = Births.new(); assert(not t:observe(nil, true, 100)); assert(not t:ready())
  t:observe({row(1, 10)}, true, 101); assert(not t:take(1, 10, 101))
end)
test('new window in an existing process produces a birth', function()
  local t = pending(); assert(t:take(2, 10, 102))
end)
test('new process and window produce a birth', function()
  local t = baseline(); t:observe({row(2, 20)}, true, 101); assert(t:take(2, 20, 101))
end)
test('birth can be consumed only once', function()
  local t = pending(); assert(t:take(2, 10, 102)); assert(not t:take(2, 10, 102))
  t:observe({row(2, 10)}, true, 103); assert(not t:take(2, 10, 103))
end)
test('repeated observation does not refresh birth age', function()
  local t = pending(); t:observe({row(2, 10)}, true, 160)
  assert(not t:take(2, 10, 161))
end)
test('temporarily missing existing window is not new', function()
  local t = baseline(); t:observe({}, true, 101); t:observe({row(1, 10)}, true, 110)
  assert(not t:take(1, 10, 110))
end)
test('long absent existing identity is still not new', function()
  local t = baseline(); t:observe({}, true, 101); t:observe({row(1, 10)}, true, 100000)
  assert(not t:take(1, 10, 100000))
end)
test('pending birth survives a brief metadata omission', function()
  local t = pending(); t:observe({}, true, 102); assert(t:take(2, 10, 103))
end)
test('failed query preserves pending births even when paused', function()
  local t = pending(); assert(not t:observe(nil, false, 102)); assert(t:take(2, 10, 103))
end)
test('paused observation clears pending births', function()
  local t = pending(); t:observe({row(2, 10)}, false, 102)
  assert(not t:take(2, 10, 103))
end)
test('windows first seen while paused do not become births on resume', function()
  local t = baseline(); t:observe({row(3, 30)}, false, 101)
  t:observe({}, true, 102); t:observe({row(3, 30)}, true, 103)
  assert(not t:take(3, 30, 103))
end)
test('paused empty baseline retains older session identities', function()
  local t = baseline(); t:observe({}, false, 101); t:observe({row(1, 10)}, true, 102)
  assert(not t:take(1, 10, 102))
end)
test('reset clears pending but retains seen history and readiness', function()
  local t = pending(); t:resetPending(); assert(t:ready())
  t:observe({row(2, 10)}, true, 103); assert(not t:take(2, 10, 103))
end)
test('reused ID with another owner is a new identity', function()
  local t = baseline(); t:observe({row(1, 20)}, true, 101)
  assert(not t:take(1, 10, 101)); assert(t:take(1, 20, 101))
end)
test('new owner invalidates pending evidence for previous owner', function()
  local t = pending(); t:observe({row(2, 20)}, true, 102)
  assert(not t:take(2, 10, 102)); assert(t:take(2, 20, 102))
end)
test('previously seen ID and owner never repeat a birth', function()
  local t = baseline(); t:observe({row(1, 20)}, true, 101); assert(t:take(1, 20, 101))
  t:observe({row(1, 10)}, true, 102); assert(not t:take(1, 10, 102))
end)
test('system layer windows cannot establish ordinary window births', function()
  local t = baseline(); t:observe({row(2, 10, 3)}, true, 101)
  assert(not t:take(2, 10, 101)); t:observe({row(2, 10, 0)}, true, 102)
  assert(not t:take(2, 10, 102))
end)
test('missing layer is conservatively remembered without a birth', function()
  local t = baseline(); t:observe({{kCGWindowNumber=2, kCGWindowOwnerPID=10}}, true, 101)
  t:observe({row(2, 10)}, true, 102); assert(not t:take(2, 10, 102))
end)
test('invalid IDs and owners never produce births', function()
  local t = baseline()
  for _, value in ipairs({0, -1, 1.5, '2', false, math.huge, 0/0}) do
    t:observe({row(value, 10), row(2, value)}, true, 101)
    assert(not t:take(value, 10, 101)); assert(not t:take(2, value, 101))
  end
  t:observe({row(nil, 10), row(2, nil)}, true, 101); assert(not t:take(2, 10, 101))
end)
test('duplicate valid rows deliver exactly once', function()
  local t = baseline(); t:observe({row(2, 10), row(2, 10)}, true, 101)
  assert(t:take(2, 10, 101)); assert(not t:take(2, 10, 101))
end)
test('conflicting owners suppress births regardless of metadata order', function()
  for _, rows in ipairs({{row(2,10),row(2,20)}, {row(2,20),row(2,10)}}) do
    local t = baseline(); t:observe(rows, true, 101)
    assert(not t:take(2,10,101)); assert(not t:take(2,20,101))
    t:observe({row(2,10)}, true, 102); assert(not t:take(2,10,102))
  end
end)
test('conflicting layers suppress births regardless of metadata order', function()
  for _, rows in ipairs({{row(2,10,0),row(2,10,3)}, {row(2,10,3),row(2,10,0)}}) do
    local t = baseline(); t:observe(rows, true, 101); assert(not t:take(2,10,101))
  end
end)
test('unknown owner alongside valid row suppresses unsafe birth', function()
  local t = baseline(); t:observe({row(2,10),row(2,nil)}, true, 101)
  assert(not t:take(2,10,101))
end)
test('birth remains valid just before sixty seconds', function()
  local t = pending(); assert(t:take(2,10,160.999))
end)
test('birth expires at sixty seconds and is not revived', function()
  local t = pending(); assert(not t:take(2,10,161))
  t:observe({row(2,10)}, true, 162); assert(not t:take(2,10,162))
end)
test('clock reversal cannot prolong pending birth', function()
  local t = pending(); assert(not t:take(2,10,100)); assert(not t:take(2,10,102))
end)
test('invalid observation time records baseline without creating births', function()
  local t = baseline(); t:observe({row(2,10)}, true, nil)
  t:observe({row(2,10)}, true, 102); assert(not t:take(2,10,102))
end)
test('wrong PID lookup does not consume matching pending evidence', function()
  local t = pending(); assert(not t:take(2,20,102)); assert(t:take(2,10,102))
end)
test('nonidentity metadata does not affect tracker state', function()
  local t = baseline(); local r = row(2,10)
  r.kCGWindowName = 'never retain me'; r.extra = {private='never retain me'}
  t:observe({r}, true, 101); r.kCGWindowOwnerPID = 99
  local function check(value)
    if type(value) == 'table' then for k,v in pairs(value) do check(k); check(v) end
    else assert(value ~= 'never retain me' and value ~= 'kCGWindowName' and value ~= 'private') end
  end
  check(t); assert(t:take(2,10,102))
end)

print(string.format('%d window birth tests passed', count))
